### ISSUE TITLE
Register problems

### ISSUE THREAD

**Issue by andbraga** [samgclarke/flask-starter#1]
Hi, I found problems with your application.

If you try to register with an email that already exists, the aplication crashes. The debugger returns "UnboundLocalError: local variable 'user' referenced before assignment".

The other problem occurs if you try to register with an already existing username. No message saying that a confimation email will be sent apears. Neither the confirmation email is sent nor the user is added to the database.

**Comment by samgclarke** [comment]
Thanks. I have committed fixes for both issues. Let me know if it's now working. You will need to re-create your database.

**Comment by andbraga** [comment]
Your solution is working, but now it doesnt send a confirmation email when a user is registered neither the message saying that a email will be sent right after a user registers.

**Comment by samgclarke** [comment]
Did you ensure your `APP_SETTINGS` are not set to `DevelopmentConfig`? Have a look at views/auth.py:

```
if app.config['TESTING']:
    msg = 'Email not sent. You are in TESTING mode!'
    print(msg)
    logger.info(msg)
    return True
```

**Comment by andbraga** [comment]
Yes, I am using DevelopmentConfig, it worked before.

If you check the config.py file, the only configuration that sets TESTING to true it's the TestingConfig.

**Comment by samgclarke** [comment]
Are you sure that your email settings are correct? In `config.py`:

```
#  gmail authentication
MAIL_USERNAME = os.environ['APP_MAIL_USERNAME']
MAIL_PASSWORD = os.environ['APP_MAIL_PASSWORD']

#  mail accounts
MAIL_DEFAULT_SENDER = os.environ['MAIL_DEFAULT_SENDER']
```

Note that I just updated the last variable on the `master` branch. You will need to ensure your email security settings allow the app to send emails:

https://support.google.com/accounts/answer/6010255

**Comment by andbraga** [comment]
Your code is working fine. I had changed the activate.html file by mistake, my bad.
Thanks for your attention.
