### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by VitorHugoAguiar** [samgclarke/flask-starter#3]
The "Change Password" is not working.. When i try to change the password, it says that the is a missing field, when all the fields are with the new password.. Do you know why??

**Comment by samgclarke** [comment]
I have tested the change password workflow and it seems to be working. Please provide the error traceback you are getting.

**Comment by VitorHugoAguiar** [comment]
It's was my mistake. I change the auth.py file and thats why was not working. Now its working fine xD thank you for time xD
